### PR TITLE
fix: header and footer accessibility fixes: color contrast and image titles

### LINKED ISSUE #426: Bug: A few small accessibility issues
### Describe the bug

I ran the [aXe Chrome devtools](https://www.deque.com/axe/devtools/) on hot.opensauced.pizza and it found a few issues listed as _Serious_:

* The top-right _Sign In_ button's color contrast is only 3.36. [Text elements must have sufficient color contrast against the background.](https://dequeuniversity.com/rules/axe/4.4/color-contrast)
* Six links don't have text, so non-visual users won't know what they are. [Links must have discernible text.](https://dequeuniversity.com/rules/axe/4.4/link-name)

### Steps to reproduce

1. Visit hot.opensauced.pizza
2. Run aXe on the page, such as with the browser dev tools
3. View violations listed under _Critical_

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #426

## Mobile & Desktop Screenshots/Recordings

I wasn't sure what style change for the _Sign In_ button would be best. Adding the text shadow meant I didn't need to add any new colors to the palette. In theory any change that increases color contrast just a bit could work, such as:

* Using a different (darker) orange
* Using a different color combo altogether

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Before screenshot of white text on orange background
</td>
<td>
After screenshot of white shadowed text on orange background
</td>
</tr>
</tbody>
</table>

## Added tests?

No(t yet). I'd love to add aXe in e2e tests but see the infra is actively being worked on in #403 -> #422

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Cronk from Emperor's New Groove suavely saying "oh yeah it's all coming together"

### CODE REVIEW

File: src/components/Footer.tsx [hunk 1]
```diff
@@ -23,12 +23,36 @@ const footerContext = [
   },
   {
     socials: [
-      { url: "https://twitter.com/saucedopen", icon: <AiOutlineTwitter className="text-2xl hover:text-light-slate-10 text-light-slate-9" /> },
-      { url: "https://github.com/open-sauced", icon: <AiOutlineGithub className="text-2xl hover:text-light-slate-10  text-light-slate-9" /> },
-      { url: "https://www.instagram.com/opensauced/", icon: <AiFillInstagram className="text-2xl hover:text-light-slate-10  text-light-slate-9" /> },
-      { url: "https://www.youtube.com/opensauced", icon: <AiFillYoutube className="text-2xl hover:text-light-slate-10  text-light-slate-9" /> },
-      { url: "https://discord.com/invite/U2peSNf23P", icon: <FaDiscord className="text-2xl hover:text-light-slate-10  text-light-slate-9" /> },
-      { url: "https://dev.to/opensauced/", icon: <FaDev className="text-2xl hover:text-light-slate-10  text-light-slate-9" /> },
```
Comment (JoshuaKGoldberg) [inline src/components/Footer.tsx:31]: lil code cleanup: all the `className`s are the same, so I moved them to the JSX rendering area.

Comment (bdougie) [reply src/components/Footer.tsx:31]: This is nice. Thanks for the clean up + fix

**Review by bdougie — APPROVED** [review]
