### PR TITLE
fix: enables cmd+k and crtl+k from the right side of the keyboard

### LINKED ISSUE #339: Bug: Cmd + K/Ctrl + K for docs don't work on right side of keyboard
### Describe the bug

Currently the Hero component only watches for Cmd + K / Ctrl + K from the left side Cmd/Ctrl keys. If you try and do CmdRight + K, nothing will happen

### Steps to reproduce

1. Go to hot.opensauced.pizza
2. Press CmdRight + K or CtrlRight + K
3. Nothing happens

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by benmarg**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Enables the use of CtrlRight + K and CmdRight + K for the Hero component. 

## Related Tickets & Documents

Fixes #339 . 

https://github.com/open-sauced/hot/issues/339

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: src/components/Hero.tsx [hunk 1]
```diff
@@ -35,6 +35,10 @@ const Hero = () => {
 
   useKeys(["ControlLeft", "KeyK"], handleCmdK, { target: containerRef });
 
+  useKeys(["ControlRight", "KeyK"], handleCmdK, { target: containerRef });
```
Comment (NsdHSO) [inline src/components/Hero.tsx:38]: It wouldn't be clean to create a function to pass these parameters and apply DRY
````
function useKey(superKey, key, target, hasFocus) {
  useKeys(
    [superKey, key],
    async (e: KeyboardEvent) => {
      if (!hasFocus) {
      } else {

      }
      // prevent browser from handling CMD/CTRL + K
      e.preventDefault();
    },
    { target: target }
  );
}

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍 

Thanks for awesome great contribution! We forgot to merge this on stream but will do so now!
