### PR TITLE
fix: Load more button visibility issue  and now loads data upon clicking

### LINKED ISSUE #446: Bug: Should not show load more button if there is no more data
### Describe the bug

"Load More" button should disappear if there is no more data 

https://user-images.githubusercontent.com/44801561/216786466-2a8e7ecc-fbb4-47ad-b8c7-ef224fd273aa.mp4

### Steps to reproduce

1. Go to the homepage
2. Navigate to any of the tabs from "Recent", "Upvoted", "Discussed", "Popular"
3. Scroll down to the end of the page
4. Click on **Load More** button, it won't load any data

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by deepakrudrapaul**
## Description

This PR fixes the load more button visibility issue  and now loads data upon clicking

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #446 

## Mobile & Desktop Screenshots/Recordings

Before :
[before.webm](https://github.com/open-sauced/hot/assets/25549935/a2081cde-28d1-402b-a8ec-94e12a861a20)

After :
[after.webm](https://github.com/open-sauced/hot/assets/25549935/4a1ce225-298a-40ac-88aa-7db772a22384)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
:smiley:

### CODE REVIEW

File: src/components/ListRepositories.tsx [hunk 1]
```diff
@@ -4,24 +4,24 @@ import Skeleton from "react-loading-skeleton";
...
   fetchedData,
   title,
+  hasNextPage,
 }: ListRepositoriesProps): JSX.Element => {
   if (!fetchedData.length) {
     return (
       <div className="mx-auto max-w-7xl px-4 mt-10">
         <div className="flex flex-col gap-y-5 overflow-hidden mb-12">
-          {Array.from(Array(10).keys()).map(item => (
+          {Array.from(Array(25).keys()).map(item => (
```
Comment (NsdHSO) [inline src/components/ListRepositories.tsx:24]: it seems that in the past I see that it was 10 why did you change it to 25?? does this have a feature ??

**Review by NsdHSO — APPROVED** [review]
LGTM

File: src/components/ListRepositories.tsx (hunk 1 above)
Comment (deepakrudrapaul) [reply src/components/ListRepositories.tsx:24]: I made changes to match the length of the fetchedData list, enhancing the user experience. With the array length set to 25, users no longer need to scroll down to see the load more button.

I have included a video demonstrating the current behaviour. I hope this will provide clarity.
[Screencast from 20-07-23 11:15:43 AM IST.webm](https://github.com/open-sauced/hot/assets/25549935/8c3fc707-64bc-4e5e-a79a-6c408b1fdea9)

Comment (NsdHSO) [reply src/components/ListRepositories.tsx:24]: @bdougie are you ok with this change?

**Comment by bdougie** [comment]
Sorry for missing this one. Looks good

**Review by bdougie — APPROVED** [review]
