### PR TITLE
fix: correct swr fetcher not throwing on error

### LINKED ISSUE #305: Bug: Open in application you received white screen
### Describe the bug

Sometimes https call fails and this problem not caught.
In console received this 
image
In network tab received this 
image

### Steps to reproduce

1. Open in App 
2. Sometimes you will get white screen.

### Affected services

hot.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

I think we will should to implemented a global Handler error 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by 0-vortex**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

So I disabled a repository in the database to see if SWR correctly errors out - turns out, it doesn't and I went leg up forgot to add the issue, or fix it 🍕 

## Related Tickets & Documents

fixes #305

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: src/hooks/useSWR.ts [hunk 1]
```diff
@@ -3,6 +3,15 @@ import { Fetcher } from "swr";
 const apiFetcher: Fetcher = async (apiUrl: string) => {
   const res = await fetch(`${import.meta.env.VITE_API_URL}/${apiUrl}`, { headers: { accept: "application/json" } });
 
+  if (!res.ok) {
+    const error = new Error("HttpError");
+
+    error.message = `${res.status} ${res.statusText}`;
+    error.stack = JSON.stringify(await res.json());
```
Comment (NsdHSO) [inline src/hooks/useSWR.ts:10]: This await is not redundant?

**Comment by NsdHSO** [comment]
I think for the moment you can merge this PR, To don't brake app.

File: src/hooks/useSWR.ts (hunk 1 above)
Comment (0-vortex) [reply src/hooks/useSWR.ts:10]: it's a Promise ... `.text()` isn't IIRC
